// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByFt3iTzdd5k9J5itBOeYBWCqIYawtdMI',
    appId: '1:880319531978:web:fa1626fe8522a988835d33',
    messagingSenderId: '880319531978',
    projectId: 'dreamcakes-mob',
    authDomain: 'dreamcakes-mob.firebaseapp.com',
    storageBucket: 'dreamcakes-mob.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbsnzkegb_KVn7C-iILIa3skcCYTYgg64',
    appId: '1:880319531978:android:c02456660223f141835d33',
    messagingSenderId: '880319531978',
    projectId: 'dreamcakes-mob',
    storageBucket: 'dreamcakes-mob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ldx7xKKsDWnYDIAvQL21sxjkMcSLvvY',
    appId: '1:880319531978:ios:a50a0bac0783cb79835d33',
    messagingSenderId: '880319531978',
    projectId: 'dreamcakes-mob',
    storageBucket: 'dreamcakes-mob.appspot.com',
    iosClientId: '880319531978-0qu2a9ed6ptgpoggtqgqctaantmaf1b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ldx7xKKsDWnYDIAvQL21sxjkMcSLvvY',
    appId: '1:880319531978:ios:a50a0bac0783cb79835d33',
    messagingSenderId: '880319531978',
    projectId: 'dreamcakes-mob',
    storageBucket: 'dreamcakes-mob.appspot.com',
    iosClientId: '880319531978-0qu2a9ed6ptgpoggtqgqctaantmaf1b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
